name: Deployment

on:
  push:
    branches:
      - main

# Sets permissions of the `GITHUB_TOKEN` to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pages: write

# Allow one concurrent deployment
concurrency: production

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly

      - name: Install Trunk
        run: |
          wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
          sudo mv trunk /usr/bin/

      - name: Build
        run: trunk build --release --public-url "${{ steps.pages.outputs.base_path }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
