name: Deployment

on:
  workflow_run:
    branches: [main]
    types: [completed]
    workflows: [Test]

# Sets permissions of the `GITHUB_TOKEN` to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pages: write

# Allow one concurrent deployment
concurrency:
  cancel-in-progress: true
  group: production

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    environment: 
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - id: pages
        name: Configure GitHub Pages
        uses: actions/configure-pages@v2

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
          toolchain: nightly

      - name: Install Trunk
        run: |
          wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
          sudo mv trunk /usr/bin/

      - name: Build
        run: trunk build --release --public-url "${{ steps.pages.outputs.base_path }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build

      - id: deployment
        name: Deploy
        uses: actions/deploy-pages@v1
