name: Test

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu, wasm32-unknown-unknown
          toolchain: nightly

      - name: Test
        run: cargo test --target=x86_64-unknown-linux-gnu -- --nocapture

      - name: Install `wasm-pack`
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - env:
          WASM_BINDGEN_TEST_TIMEOUT: 600
        name: Run integration tests
        run: wasm-pack test --release --headless --chrome
